export const airlines = {
  AAL: "American Airlines",
  DAL: "Delta Air Lines",
  UAL: "United Airlines",
  DLH: "Lufthansa",
  AFR: "Air France",
  SWA: "Southwest Airlines",
  THY: "Turkish Airlines",
  EZY: "easyJet",
  ANZ: "Air New Zealand",
  AUA: "Austrian Airlines",
  AVA: "Avianca - Aerovias Nacionales de Colombia",
  ACA: "Air Canada",
  AIC: "Air India",
  CCA: "Air China",
  QTR: "Qatar Airways",
  QFA: "Qantas",
  BAW: "British Airways",
  IBE: "Iberia Airlines",
  KLM: "KLM Royal Dutch Airlines",
  CSN: "China Southern Airlines",
  ARG: "Aerolineas Argentinas",
  KAL: "Korean Air",
  CSH: "Shanghai Airlines",
  ETD: "Etihad Airways",
  UAE: "Emirates",
  EIN: "Aer Lingus",
  VIR: "Virgin Atlantic Airways",
  ANA: "All Nippon Airways",
  WJA: "WestJet",
  HAL: "Hawaiian Airlines",
  KAC: "Kuwait Airways",
  ASA: "Alaska Airlines",
  AMX: "Aeromexico",
  JAL: "Japan Airlines",
  AAN: "Amsterdam Airlines",
  AAR: "Asiana Airlines",
  MSR: "Egyptair",
  RYR: "Ryanair",
  IBU: "Indigo",
  FFT: "Frontier Airlines",
  ETH: "Ethiopian Airlines",
  VOI: "Volaris",
  SWR: "Swiss International Air Lines",
  SAS: "Scandinavian Airlines",
  AXM: "AirAsia",
  JBU: "JetBlue Airways"
};
